const product = [
    {
        "id": 1,
        "date": "2023-08-09",
        "institution": "Bank A",
        "account": "1234",
        "merchant": "Amazon",
        "amount": 50.99,
        "type": "purchase",
        "categoryId": 3,
        "category": "Online Shopping",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 2,
        "date": "2023-08-08",
        "institution": "Bank B",
        "account": "5678",
        "merchant": "Starbucks",
        "amount": 4.75,
        "type": "expense",
        "categoryId": 1,
        "category": "Food & Drinks",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 3,
        "date": "2023-08-07",
        "institution": "Bank A",
        "account": "1234",
        "merchant": "Gas Station",
        "amount": 35.60,
        "type": "purchase",
        "categoryId": 2,
        "category": "Transportation",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 4,
        "date": "2023-08-06",
        "institution": "Bank C",
        "account": "9876",
        "merchant": "Salary Deposit",
        "amount": 2500.00,
        "type": "income",
        "categoryId": 4,
        "category": "Income",
        "isPending": false,
        "isTransfer": false,
        "isExpense": false,
        "isEdited": false
    },
    {
        "id": 5,
        "date": "2023-08-05",
        "institution": "Bank A",
        "account": "1234",
        "merchant": "Apple Store",
        "amount": 1200.00,
        "type": "purchase",
        "categoryId": 3,
        "category": "Electronics",
        "isPending": true,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 6,
        "date": "2023-08-04",
        "institution": "Bank B",
        "account": "5678",
        "merchant": "Gym Membership",
        "amount": 30.00,
        "type": "subscription",
        "categoryId": 5,
        "category": "Health & Fitness",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": true
    },
    {
        "id": 7,
        "date": "2023-08-03",
        "institution": "Bank A",
        "account": "1234",
        "merchant": "Transfer from Bank B",
        "amount": 500.00,
        "type": "transfer",
        "categoryId": 6,
        "category": "Transfers",
        "isPending": false,
        "isTransfer": true,
        "isExpense": false,
        "isEdited": false
    },
    {
        "id": 8,
        "date": "2023-08-02",
        "institution": "Bank C",
        "account": "9876",
        "merchant": "Rent Payment",
        "amount": 1000.00,
        "type": "expense",
        "categoryId": 7,
        "category": "Housing",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 9,
        "date": "2023-08-01",
        "institution": "Bank A",
        "account": "1234",
        "merchant": "Grocery Store",
        "amount": 75.50,
        "type": "purchase",
        "categoryId": 8,
        "category": "Groceries",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": true
    },
    {
        "id": 10,
        "date": "2023-07-31",
        "institution": "Bank B",
        "account": "5678",
        "merchant": "Concert Tickets",
        "amount": 80.00,
        "type": "purchase",
        "categoryId": 9,
        "category": "Entertainment",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    }
];

export default product;
