const product = [
    {
        "id": 1,
        "date": "2023-08-01",
        "institution": "Bank A",
        "account": "Savings",
        "merchant": "Grocery Store",
        "amount": 50.0,
        "type": "Debit",
        "categoryId": 501,
        "category": "Groceries",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 2,
        "date": "2023-08-02",
        "institution": "Credit Union B",
        "account": "Checking",
        "merchant": "Restaurant XYZ",
        "amount": 30.0,
        "type": "Debit",
        "categoryId": 502,
        "category": "Restaurants",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },

    {
        "id": 3,
        "date": "2023-08-03",
        "institution": "Gas Station",
        "account": "Debit Card",
        "merchant": "Gas Station ABC",
        "amount": 40.0,
        "type": "Debit",
        "categoryId": 1,
        "category": "Auto & Transport",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 4,
        "date": "2023-08-04",
        "institution": "Utility Company",
        "account": "Checking",
        "merchant": "Water Bill",
        "amount": 70.0,
        "type": "Debit",
        "categoryId": 2,
        "category": "Bills & Utilities",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 5,
        "date": "2023-08-05",
        "institution": "Cinema",
        "account": "Credit Card",
        "merchant": "Movie Tickets",
        "amount": 25.0,
        "type": "Debit",
        "categoryId": 301,
        "category": "Entertainment",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 6,
        "date": "2023-08-06",
        "institution": "Bank A",
        "account": "Savings",
        "merchant": "ATM Fee",
        "amount": 2.5,
        "type": "Debit",
        "categoryId": 401,
        "category": "Fees & Charges",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 7,
        "date": "2023-08-07",
        "institution": "Restaurant",
        "account": "Debit Card",
        "merchant": "Fast Food Joint",
        "amount": 12.0,
        "type": "Debit",
        "categoryId": 501,
        "category": "Food & Dining",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 8,
        "date": "2023-08-08",
        "institution": "Home Improvement Store",
        "account": "Credit Card",
        "merchant": "DIY Supplies",
        "amount": 60.0,
        "type": "Debit",
        "categoryId": 602,
        "category": "Home",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 9,
        "date": "2023-08-09",
        "institution": "Employer",
        "account": "Savings",
        "merchant": "Monthly Salary",
        "amount": 2000.0,
        "type": "Credit",
        "categoryId": 7,
        "category": "Income",
        "isPending": false,
        "isTransfer": false,
        "isExpense": false,
        "isEdited": false
    },
    {
        "id": 10,
        "date": "2023-08-10",
        "institution": "Online Store",
        "account": "Credit Card",
        "merchant": "Electronics Shop",
        "amount": 300.0,
        "type": "Debit",
        "categoryId": 801,
        "category": "Shopping",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    },
    {
        "id": 11,
        "date": "2023-08-11",
        "institution": "Bank B",
        "account": "Savings",
        "merchant": "Transfer To Friend",
        "amount": 50.0,
        "type": "Debit",
        "categoryId": 9,
        "category": "Transfer",
        "isPending": false,
        "isTransfer": true,
        "isExpense": false,
        "isEdited": false
    },
    {
        "id": 12,
        "date": "2023-08-12",
        "institution": "Restaurant",
        "account": "Debit Card",
        "merchant": "Coffee Shop",
        "amount": 5.0,
        "type": "Debit",
        "categoryId": 502,
        "category": "Restaurants",
        "isPending": false,
        "isTransfer": false,
        "isExpense": true,
        "isEdited": false
    }    

];

export default product;
